# Generated by Django 2.2.2 on 2019-07-20 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('humidity', models.FloatField()),
                ('light', models.FloatField()),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservoir.Reservoir')),
            ],
        ),
    ]
